baseurl: https://unlistenablepodcast.com
title: The Unlistenable Podcast
author: Alex Lishinski
canonifyurls: yes
languagecode: en
theme: hugo-tanka
enableEmoji: yes
hasCJKLanguage: no
pygmentsstyle: vs
pygmentscodefences: yes
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
params:
  faviconfile: images/favicon.png
  highlightjs: yes
  highlightjslanguages:
    - r
    - python
    - stan
  progressively: no
  sitename: The Unlistenable Podcast
  uselatex: yes
markup:
  goldmark:
    renderer:
      unsafe: yes
menu:
  primary:
    - name: Home
      url: /
      weight: 1
    - name: About
      url: /about/
      weight: 2
    - name: FAQ
      url: /faq/
      weight: 3
    - name: RSS Feed
      url: https://media.rss.com/the-unlistenable-podcast/feed.xml
      weight: 4
    # - name: Subscribe
    #   url: /index.xml
    #   weight: 5
